global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Recape.Attributes;
global using Recape.Models;
global using Recape.ViewModels;
global using System.ComponentModel.DataAnnotations;
global using System.Diagnostics;
